#######
# Cloudify Blueprint which runs a bash script

imports:
    - cloudify.openstack

# The blueprint contains two nodes, a vm and a web server hosted in it.
blueprint:
    name: tty_js-timestamp-1
    nodes:
        -   name: vm
            type: cloudify.types.host

        -   name: tty_js
            type: bash_runner
            properties:
                scripts: ["start.sh"]
            relationships:
                -   type: cloudify.relationships.contained_in
                    target: vm

#######
# Types and implementation details.
#
plugins:
    bash_runner:
        derived_from: cloudify.plugins.agent_plugin
        properties:
            url: https://github.com/rantav/cosmo-plugin-bash-runner/archive/master.zip

types:
    bash_runner:
        derived_from: cloudify.types.web_server
        properties:
            - scripts: []
        interfaces:
            cloudify.interfaces.lifecycle:
                -   start: bash_runner.tasks.run

type_implementations:
    vm_openstack_host_impl:
        type: cloudify.openstack.server
        node_ref: vm
        properties:
            install_agent: true
            worker_config:
                user: ubuntu
                port: 22
                key: ~/.ssh/cloudify-agents-kp.pem
            server:
                name: tty_js
                image_name: 'Ubuntu Precise 12.04 LTS Server 64-bit 20121026 (b)'
                flavor_name: standard.xsmall
                key_name: cloudify-agents-kp-rantav2
            nova_config:
                region: az-2.region-a.geo-1
    bash_runner_impl:
        type: bash_runner
        node_ref: tty_js
